services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: energisa_back_postgres
      POSTGRES_USER: energisa_back_postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - energisa_back_postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U energisa_back_postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_ROLE: ${ADMIN_ROLE}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS}
      UPLOAD_DIR: ${UPLOAD_DIR}
      AUTO_TRAIN_RISK_MODEL: ${AUTO_TRAIN_RISK_MODEL}
      FORCE_TRAIN_RISK_MODEL: ${FORCE_TRAIN_RISK_MODEL}
      HF_TOKEN: ${HF_TOKEN}
    volumes:
      - ./uploads:/data/uploads

volumes:
  energisa_back_postgres: